### ISSUE TITLE
RFC: Annotations

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#113]
There are cases that cannot be resolved autimatically by static analysis. In these casses new annotations cound be used to guide resolvers to analyse latte correctly.

### `@phpstan-latte-ignore`
Allowed context: variable assign, method call, render call, method, class

```php
class MyControl extends Control
{
    public function render(string $param): void {
        if ($param) {   
            /** @phpstan-latte-ignore */
            $this->template->something = $param; // <-- this variable will not be collected (by default all template variables assigned inside method are collected)
        } else {
            $this->render(__DIR__ . '/MyControl.latte');
        }
    }
}
```

```php
class MyControl extends Control
{
    public function render(string $param): void {
        if ($param) {       
            /** @phpstan-latte-ignore */   
            $this->render(__DIR__ . $param); // <-- this will not be attepted to resolve (reported as expression that cannot be resolved)
        } else {
            $this->render(__DIR__ . '/MyControl.latte');
        }
    }
}
```

```php
class MyControl extends Control
{
    /** @phpstan-latte-ignore */ // <-- whole method is ignored by resolvers and collectors
    public function render(string $param): void {
        $this->template->something = $param; // <-- this variable will not be collected
        if ($param) {       
            $this->render(__DIR__ . $param); // <-- this will not be resolved
        } else {
            $this->render(__DIR__ . '/MyControl.latte'); // <-- this will not be resolved
        }
    }
}
```

```php
class MyControl extends Control
{
    public function render(string $param): void {
        /** @phpstan-latte-ignore */         
        $this->doRender(); // <-- this method call wil not be follwed by resolvers (resolving renders or collecting variables inside called method)
    }

    private function doRender(): void {
        $this->template->something = $param; // <-- this variable will not be collected when resolving render()
        if ($param) {       
            $this->render(__DIR__ . $param); // <-- this will not be resolved when resolving render()
        } else {
            $this->render(__DIR__ . '/MyControl.latte'); // <-- this will not be resolved when resolving render()
        }
    }
}
```

```php
/** @phpstan-latte-ignore */ // <-- whole class is ignored by resolvers and collectors
class MyControl extends Control
{
    public function render(string $param): void {
        $this->template->something = $param; // <-- this variable will not be collected
        if ($param) {       
            $this->render(__DIR__ . $param); // <-- this will not be resolved
        } else {
            $this->render(__DIR__ . '/MyControl.latte'); // <-- this will not be resolved
        }
    }

    public function renderAlternative(string $param): void {
        $this->template->something = $param; // <-- this variable will not be collected
        if ($param) {       
            $this->render(__DIR__ . $param); // <-- this will not be resolved
        } else {
            $this->render(__DIR__ . '/MyControl.latte'); // <-- this will not be resolved
        }
    }
}
```

### `@phpstan-latte-template`
Allowed context: render call, method, class

Value specifies what template or templated should be resolved and checkid in given context.

Multiple annoations can be used on single element or at different levels. When used all of them will be resolved.

Can use wildcard `*` to match multiple files
Can use placeholders:
`{dir}` = `__DIR__` (example `/app/dir/controls`)
`{file}` = `__FILE__` (example `/app/dir/controls/MyControl.php`)
`{fileName}` = `basename(__FILE__)` (example `MyControl.php`)
`{fileNameNoSuffix}` = file anme with suffix removed (example `MyControl`)
`{classShortName}` = class short name withnout namespace (example `MyControl`)

Question: regex support?

```php
class MyControl extends Control
{
    public function render(string $param): void {
        /** @phpstan-latte-template {dir}/templates/{classShortName}.*.latte */
        $this->render($this->getTemplatePath($param)); // <-- will resolve all templates matching given pattern and will not report error of expression that cannot be evaluated
    }
}
```

```php
class MyControl extends Control
{
    /** @phpstan-latte-template {dir}/templates/{classShortName}.*.latte */ // <-- will resolve all templates matching given pattern + anything resolved from method body
    public function render(string $param = null): void {
        if($param !== null) {     
            $this->render($this->getTemplatePath($param)); // <-- will be resolved normally (will report error of unresolved expression)
        } else {
            $this->render(__DIR__ . '/MyControl.latte'); // <-- will be resolved normally
        }
}
```

```php
class MyControl extends Control
{
    /** @phpstan-latte-template {dir}/templates/{classShortName}.*.latte */ // <-- will resolve all templates matching given pattern + anything resolved from method body
    public function render(string $param = null): void {
        if($param !== null) {     
            /** @phpstan-latte-ignore */
            $this->render($this->getTemplatePath($param)); // <-- will be ignored so no error now
        } else {
            $this->render(__DIR__ . '/MyControl.latte'); // <-- will be resolved normally
        }
    }
}
```

```php
/** @phpstan-latte-template {dir}/templates/{classShortName}.*.latte */ // <-- will resolve all templates matching given pattern in all class render methods + anything resolved from method bodies
class MyControl extends Control
{
    public function render(string $param = null): void {
        if($param !== null) {     
            /** @phpstan-latte-ignore */
            $this->render($this->getTemplatePath($param)); // <-- will be ignored so no error now
        } else {
            $this->render(__DIR__ . '/MyControl.latte'); // <-- will be resolved normally
        }
        // < -- all tempaltes matching {dir}/templates/{classShortName}.*.latte will be resolved from context of this method
    }
    public function renderAlternative(string $param = null): void {
        // < -- all tempaltes matching {dir}/templates/{classShortName}.*.latte will be resolved from context of this method too
    }
}
```

### `@phpstan-latte-var`
Allowed context: render call, method, class

Defines variable type passed to template in given context.

Multiple annoations can be used on single element or at different levels. 

When same variable name is defined at multiple levels then lowest level definition is used. So if class annotationd defines variable as `string|int` but annotation on render call specifies it as `string` then in template it will be evaluated as `string`.

If type `void` is used then tempalte will be undefined in template.

Annotations takes precedence over anything collected from code. Even when used on different level. So when class annoation defines variable type it will overwrite variable type collected in method calls or render call parameters.

Question: Is this behaviour expected? Or should annotation overwrite only same level?

TODO examples

### `@phpstan-latte-component`

Same behaviour as `@phpstan-latte-var` but for components.

**Comment by lulco** [comment]
I personally really don't like inline ignore annotations (and I don't use them because it is possible to use phpstan.neon parameter ignoreErrors). Do you think there could be also parameter in latte?

**Comment by MartinMystikJonas** [comment]
For ignoring errors standard mechanism could be used too. This annotations are mean to guide resolvers in cases where static analysis cannot solve things automatically. I do not think it is practical to use it in parameters because it would have to always specify exact context (file and line) and it would be nightmare to maintain with code changes.

Parameters might be used to ignore whole classes but it will not be practical for methods and specific assignments/calls.

**Comment by lulco** [comment]
True, so I will try to write apps in way that phpstan-latte will understand :)

**Comment by MartinMystikJonas** [comment]
@jakubvojacek How do you like it? Any ideas for improvement?

**Comment by jakubvojacek** [comment]
From the three annotations listed, I would use `@phpstan-latte-ignore`, for the other ones I dont have use yet but I was not able to go through the list of reported errors for my codebase and resolve them. Perhaps while resolving them, I could use the other annotations.

Thanks

**Comment by MartinMystikJonas** [comment]
I just realized I need these palceholders:

> {dir} = __DIR__ (example /app/dir/controls)
{file} = __FILE__ (example /app/dir/controls/MyControl.php)
{fileName} = basename(__FILE__) (example MyControl.php)
{fileNameNoSuffix} = file anme with suffix removed (example MyControl)
{classShortName} = class short name withnout namespace (example MyControl)

in two versions:
1) relative to file/class where annotation is written
2) relstive to file/class that is resolved (could be offspring or caller)

Any idea for names for them?

**Comment by lulco** [comment]
Sorry I'm not sure where it would be used, can you place some examples here?

**Comment by MartinMystikJonas** [comment]
Use cases are for example some kind of Control that use expression to set template path that cannot be resolved automatically.

Case 1) Control uses expression to resolve tempalte path that is relative to `__DIR__` but contains some method calls or variables. BUt should be resolved relative to defining class even in offsprings (because __DIR__ is alwas relative to defining class)

```php
/** 
 * @phpstan-latte-tempalte {dir}/template/Something.*.latte // here dir should be relative to defining file
 */
$path = __DIR__ . '/templates/Something . '.' . $this->getType() . '.latte';
```

Case 2) Control uses expression relative to offspring file/class. We have cases with something like:

```php
/** 
 * @phpstan-latte-tempalte {dir}/template/{classShortName}.latte // here dir should be relative to resolved file
 */
$path = dirname((string)$reflection->getFileName()) . '/templates/' . $reflection->getShortName() . '.latte';
```

**Comment by MartinMystikJonas** [comment]
@jakubvojacek Annotation `@phpstan-latte-ignore` is ready to be tested. Let me know if you stumble upon any issues or unexpected behaviour.
