### ISSUE TITLE
Included latte, false postive 

### ISSUE THREAD

**Issue by jakubvojacek** [efabrica-team/phpstan-latte#114]
```
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   FrontModule/Components/Tools/systemTabs.latte rendered from Motv\FrontModule\Presenters\ToolsPresenter included in FrontModule/Presenters/templates/Tools/backups.latte  
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  12     Strict comparison using === between 'backups' and 'system' will always evaluate to false.                                                                                
  14     Strict comparison using === between 'backups' and 'backups' will always evaluate to true.                                                                                
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   FrontModule/Components/Tools/systemTabs.latte rendered from Motv\FrontModule\Presenters\ToolsPresenter::system included in FrontModule/Presenters/templates/Tools/system.latte  
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  12     Strict comparison using === between 'system' and 'system' will always evaluate to true.                                                                                         
  14     Strict comparison using === between 'system' and 'backups' will always evaluate to false.                                                                                       
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   FrontModule/Components/Tools/systemTabs.latte rendered from Motv\FrontModule\Presenters\ToolsPresenter::processes included in FrontModule/Presenters/templates/Tools/processes.latte  
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  12     Strict comparison using === between 'system' and 'system' will always evaluate to true.                                                                                               
  14     Strict comparison using === between 'system' and 'backups' will always evaluate to false.                                                                                             
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
```

systemTabs.latte
```
<div class="page-tabs-inside">
        <div class="page-tabs-tab {if $actual === 'system'}active{/if}"><a n:href=":Front:Tools:system">System</a></div>
        <div class="page-tabs-tab {if $actual === 'backups'}active{/if}"><a n:href=":Front:Tools:backups">Backups</a></div>
</div>
```

processes.latte
```
{include 'systemTabs.latte', actual: 'system'}
```

backups.latte
```
{include 'systemTabs.latte', actual: 'backups'}
```

Its not really a problem, I could ignore the errors (since I guess it will be hard to solve).

**Comment by MartinMystikJonas** [comment]
We evaluate templates with specific variable types so when evalution specific include we know exactly what is in variable. But it also mean that this kind of false possitive can occur. We can pass less specific variable type but it could hide different kind of errors. 

@lulco Maybe just ignore this kind of errors globally for literal values? All comparsions between literal strings and literal numbers?

**Comment by lulco** [comment]
@MartinMystikJonas Is this caused by VerbosityLevel::precise? Shouldn't we go back to type only? and use precise only where it is really needed (closure filters you said)?

**Comment by MartinMystikJonas** [comment]
I would preffer to keep precise. With typeOnly we lost tons of valuable data. Like array shapes, callable signatures, ... 

And for literal strings it is useful too. Imagine similar code like above but with value of `$actual` passed from PHP with typo as `'sysem'`. With precise this bug is reported. With typeOnly it is ignored.

**Comment by jakubvojacek** [comment]
yes, precise seems like much better option on 99% cases, as I said, I can ignore this - the included template was used to avoid code duplication only

**Comment by lulco** [comment]
OK, but for now, I wouldn't ignore these errors globally to not hide some real errors.

**Comment by MartinMystikJonas** [comment]
@lulco I can think of one reliable way how to solve it but it would require more complex logic for included templates. 

We would first collect all include calls for given template. Ten for same included file we will make union type of types assigned to same variable name from all includes. And then we will analyse included tempalte. So it would not be evaluated twice. First with `'system'` and second time with `'backups'`.  But only once with `'system|'backups'`

**Comment by MartinMystikJonas** [comment]
Agreed global ignore could hide real bugs so better keep it reported and let user decide if it can be ignored or not

**Comment by lulco** [comment]
> @lulco I can think of one reliable way how to solve it but it would require more complex logic for included templates.
> 
> We would first collect all include calls for given template. Ten for same included file we will make union type of types assigned to same variable name from all includes. And then we will analyse included tempalte. So it would not be evaluated twice. First with `'system'` and second time with `'backups'`. But only once with `'system|'backups'`

I was thinking about it the same way, but then we can get to point where from one template there will by send system, from second one will not be sent anything and we will check included template with "system". So we will completely lost that in second template there is no value (because we create union). I think this is good way - included templates are checked in same way like templates with data from php (presenter / control)

**Comment by MartinMystikJonas** [comment]
> > @lulco I can think of one reliable way how to solve it but it would require more complex logic for included templates.
> > We would first collect all include calls for given template. Ten for same included file we will make union type of types assigned to same variable name from all includes. And then we will analyse included tempalte. So it would not be evaluated twice. First with `'system'` and second time with `'backups'`. But only once with `'system|'backups'`
> 
> I was thinking about it the same way, but then we can get to point where from one template there will by send system, from second one will not be sent anything and we will check included template with "system". So we will completely lost that in second template there is no value (because we create union). I think this is good way - included templates are checked in same way like templates with data from php (presenter / control)

Can we set variable as `'system'|void` in case that some variants do not define value at all? I am not sure PHPStan can handle it.

**Comment by lulco** [comment]
I'm not sure too, but again I would like to handle templates and included templates in the same way.

**Comment by MartinMystikJonas** [comment]
Well for standard render calls of templates we also do union of all collected variable types now.

**Comment by MartinMystikJonas** [comment]
It does not work with void https://phpstan.org/r/d59d9c53-4c17-4301-bc89-c7ebd152953c but when I think about it we can simply pass only varibales defined in all contexts

**Comment by lulco** [comment]
> Well for standard render calls of templates we also do union of all collected variable types now.

Not really, we are just union all types from one Control / Presenter. But latte template can be used from different Presenter actions / Control renders and thats how you suggest to check included templates.

**Comment by MartinMystikJonas** [comment]
Hmm true. So maybe this do not have good solution?

**Comment by lulco** [comment]
I think best solution now is to ignore these errors on user's side

**Comment by MartinMystikJonas** [comment]
Agreed

**Comment by MartinMystikJonas** [comment]
This could be use case for propagated `{varType}`. In included template use `{varType 'system|'backups' $actual}` and when checking it then check that passed value is accepted by given type.

**Comment by lulco** [comment]
I'm closing this. Message is that these errors have to be ignored on user's side at the moment.
