### ISSUE TITLE
Analysis speed

### ISSUE THREAD

**Issue by jakubvojacek** [efabrica-team/phpstan-latte#116]
Hello 

how fast is phpstan-latte on your work projects? When used, it is taking considerably longer to evaluate, like from 5 seconds before to three minutes after (on mac pro M1).

Not complaining at all, it can take ages in the CI, does not really matter most of the time, just wanted to know the comparison.

**Comment by MartinMystikJonas** [comment]
It is slow because we need to collect tons of potentially useful data acreoss whole codebase to be able to analyse all latte "template global state" changes. On my projects it is abou 1-2 minutes and I have guite high end CPU. Later we can try some optimizations but it was not priority at the moment.

**Comment by lulco** [comment]
Well it depends on what and how much rules you have turned on. Each template is compiled and analysed separately and can be analysed few times if you reuse it.

I have to admit that performance is last thing I was thinking about :) I just want to analyse latte files. Unfortunately, it will be slower when we add another features (like support for forms, etc.).

But in my case the difference between "classic" phpstan and phpstan with phpstan-latte is 1 minute 17 seconds vs 1 minute 46 seconds.

**Comment by jakubvojacek** [comment]
Ok thanks :+1:

**Comment by lulco** [comment]
From 5 seconds to 3 minutes is really big difference. I have never phpstan done under minute :)) If you use it with `--debug` I think it runs only in 1 process.

**Comment by MartinMystikJonas** [comment]
I have few ideas how we could optimize but not sure how much it will help. First what I would try is to first compile all templates and then analyse them in one go. And cache compiled templates when they are compiled with same exact context. But it is not a priority yet.
