### ISSUE TITLE
Unknown type in foreach variable when $iterator is used inside loop

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#130]
In Latte 3 (not sure about Latte 2) latte code:
```latte
{foreach $registrations as $registration}
```
is compiled as:
```php
foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($registrations, $ʟ_it ?? null) as $registration) {
```
but this wrapping interated collection inside `CachingIterator` lost information about item type. So `$registration` is mixed.

**Comment by MartinMystikJonas** [comment]
How can we solve it? First option might be to use nodeVIsitors to replace
```php
foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($registrations, $ʟ_it ?? null) as $registration) {
```
to
```php
$iterator = $ʟ_it = new Latte\Essential\CachingIterator($registrations, $ʟ_it ?? null);
foreach ($registrations  as $registration) {
```
but not sure how difficult it would be.

Another option might be to correctly define stub for CachingIterator so it would propagate type information.

**Comment by lulco** [comment]
I think I've done this before. But I don’t know where :D

**Comment by lulco** [comment]
@MartinMystikJonas what exactly is the problem? 
I checked the types inside foreach and it works:
https://github.com/efabrica-team/phpstan-latte/actions/runs/3661805309/jobs/6190373603

I have list of strings and in foreach it is string.

**Comment by MartinMystikJonas** [comment]
@lulco I  had reports errors in our real world app abou cslling methods on mixed. I thought it was because of foreach but maybe there is another cause. I will investigate more.

**Comment by lulco** [comment]
Maybe as soon as you use $iterator inside foreach? I did this PR on mobile :) I wasn't able to use more complicated constructs

**Comment by MartinMystikJonas** [comment]
I will check later today

**Comment by MartinMystikJonas** [comment]
Seems like error is somewhere else. Closing.

**Comment by lulco** [comment]
It seems I was right, when I used `$iterator` inside foreach, compiled template is different:
```
$iterations = 0;
foreach ($localStrings as $string) {
    \PhpStan\dumpType($string);
    $iterations++;
}
```
vs
```
$iterations = 0;
foreach ($iterator = $ʟ_it = new LR\CachingIterator($localStrings, $ʟ_it ?? null) as $string) {
    echo LR\Filters::escapeHtmlText($iterator->counter);
    \PhpStan\dumpType($string);
    $iterations++;
}
```

**Comment by MartinMystikJonas** [comment]
Ah yes you are right. I was checking wrong template. It it caused by use of iterator inside foreach loop.

**Comment by lulco** [comment]
something like this will help:
```
$iterator = $ʟ_it = new LR\CachingIterator($stringLists, $ʟ_it ?? null);
foreach ($stringLists as $stringList) {
```
move creating $iterator before foreach

Then there are some $iterator issues, but I think we can ignore then as they are caused be nette itself and we don't need them to fix
```
Parameter #2 $parent of class Latte\Runtime\CachingIterator constructor expects Latte\Runtime\CachingIterator|null, mixed given.
Cannot access property $first on Latte\Runtime\CachingIterator|null.
Cannot access property $counter on Latte\Runtime\CachingIterator|null. 
```

**Comment by MartinMystikJonas** [comment]
First one surely can be ignored. Other two I am not sure what can cause them. How can `$iterator `or `$ʟ_it` be null? But probably it is ok to ignore them too.

**Comment by lulco** [comment]
it seems it is present when you have multiple inner foreach and at the end it is called `$iterator = $ʟ_it->getParent();` which has return type set to `Iterator|null` so phpstan thinks $iterator can be null at this point (but it couldn't because parent is set at this point.
```
foreach ($iterator = $ʟ_it = new LR\CachingIterator($stringLists, $ʟ_it ?? null) as $stringList) {
    foreach ($iterator = $ʟ_it = new LR\CachingIterator($stringList, $ʟ_it ?? null) as $string) {
         // some stuff
    }
    $iterator = $ʟ_it = $ʟ_it->getParent();
    // some stuff
}
$iterator = $ʟ_it = $ʟ_it->getParent();
```

**Comment by MartinMystikJonas** [comment]
Oh yes then ignore it.
