### ISSUE TITLE
Block parameters have always unknown type

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#136]
When block with parameters is use type of parameters is always unknown even when type is specified in latte.

Latte template:
```latte
{define statistic-row \App\Model\Dto\StatisticsRow $row, ?bool $negative, ?bool $emphasize}
  {* ... *}
{/define}
{* ... *}
{include statistic-row 'row' => $statistic, 'negative' => true}
```

is compiled as:
```php
    /** {define statistic-row \App\Model\Dto\StatisticsRow $row, $negative, $emphasize} on line 1 */
    public function blockStatistic_row(array $ʟ_args) : void
    {
        extract($this->params);
        // [only global variable types]
        $row = $ʟ_args[0] ?? $ʟ_args['row'] ?? null; // <-- $row type is mixed
        $negative = $ʟ_args[1] ?? $ʟ_args['negative'] ?? null;
        $emphasize = $ʟ_args[2] ?? $ʟ_args['emphasize'] ?? null;
        // ...
    }

    //...
    $this->renderBlock('statistic-row', ['row' => $statistic] + [], 'html');
    // ...
```

**Comment by MartinMystikJonas** [comment]
This causes lots of "Calling method on mixed" and "Access property of mixed" errors in our setup.

But I'am not sure how to solve it. 

Ideal solution would be propagation of type information from latte but it is still waiting PR https://github.com/nette/latte/pull/309

Can we somehow simulate it on our side?

**Comment by MartinMystikJonas** [comment]
Maybe parse types from that doc comment:
```
/** {define statistic-row \App\Model\Dto\StatisticsRow $row, bool $negative, bool $emphasize} on line 1 */
```
 and add them to variables?
```php

/** @var bool $emphasize */
$row = $ʟ_args[0] ?? $ʟ_args['row'] ?? null;
/** @var bool $negative */
$negative = $ʟ_args[1] ?? $ʟ_args['negative'] ?? null;
/** @var bool $emphasize */
$emphasize = $ʟ_args[2] ?? $ʟ_args['emphasize'] ?? null;
```

**Comment by lulco** [comment]
It looks similar to included templates, I don't use it much, so I have to check it first.

**Comment by MartinMystikJonas** [comment]
You mean evaluate block as independent renders? Ignore them when checking render of tempalte, collect calls for blocks and then evaluate them indepenly as we do with included templates?

**Comment by lulco** [comment]
I don't know now, because I'm not sure how it is compiled and from where we can detect variables

**Comment by lulco** [comment]
Create failing test cast and we will see what can we do with it

**Comment by MartinMystikJonas** [comment]
@lulco Test case created in #139
