### ISSUE TITLE
Evaluate parameters mismatch for blocks

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#137]
Call of block with params is currently evaluated as
```php
$this->renderBlock('statistic-row', ['row' => $statistic] + [], 'html');
```

so it does not check if call is done with right parameter types.

Compiled block definition looks like this:
```php
    /** {define statistic-row \App\Model\Dto\StatisticsRow StatisticsRow $row, bool $negative, bool $emphasize} on line 1 */
    public function blockStatistic_row(array $ʟ_args) : void
```

Not much chance to statical analysis of that too.

Maybe for analysis purposes we can transform block signatures based on doc comment to:
```php
public function blockStatistic_row(\App\Model\Dto\StatisticsRow StatisticsRow $row, bool $negative, bool $emphasize) : void
```
and replace block call with:
```php
$this->blockStatistic_row($statistics);
```

But there could be some magic with blocks from other templates etc. It would need better examination.

**Comment by lulco** [comment]
Create failing test cast and we will see what can we do with it
