### ISSUE TITLE
Split and improve docs

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#138]
Create dir docs a split docs into parts. Like configuration, annotations, how it works ane in README keep on installation, quickstart and links to other parts.

**Comment by MartinMystikJonas** [comment]
@lulco Maybe it would be good to write something like "How it works" and describe how we use collectors, resolvers, compiler and node visitors, error transofrmations, ...

**Comment by lulco** [comment]
yes, I'm just not sure if it is final version :D in last 2 months I rewrote it twice

**Comment by MartinMystikJonas** [comment]
Yes it was idea for future
