### ISSUE TITLE
Custom form field resolving

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#142]
Possibility to use FormFinder to collect form fields from given method. So resolvers can explicitly add additional forms or additional form fields to autoamticaly collected forms.

@MartinMystikJonas TODO: Prepare test case

**Comment by MartinMystikJonas** [comment]
This is one of two last things I need to solve to have no errors in our real world projects.

I was thinking about it and I think we need to make these changes:

1) Form controls (`CollectedFormField`) creation should be collected everywhere (similar to component creation) based only on called type is Form. Now it is only collected in `createComponent` that returns `Form`
2) FormFinder should be replaced by `FormFieldFinder` able to do recursive search for added form controls `CollectedFormField` (even in methods called from `createComponent`)
3) Resolving available forms should be moved to Resolvers - resolver should identify forms (based on existence of `createComponent` returning Form, but can use different methods if needed), and then create `CollectedForm` with given `CollectedFormFields` (that can be collected from many places)

**Comment by MartinMystikJonas** [comment]
Point is that we need to be able to do something like this in Resolvers: 

```php
  $fields = array_merge(
      $this->formFieldFinder->find($class, 'createComponentForm')
      $this->formFieldFinder->find($class, 'initForm')
  );
$forms = new Form($name, $type, $fields);
```

**Comment by MartinMystikJonas** [comment]
I am not sure where logic to detect default existing forms for given control/presenter should be. I think it should be in Resolvers so resolvers have full control about it. But at the same time I feel it should be independent.

Maybe have `FormCollector` and  `FormFinder` that would return only places where forms are created (basically only `createComponent` with return type `Form`) and will not attempt to return form fields (current implementation of analysist stmts of method have same problem with frozen scope we discussed earlier). This will be `CollectedForm` - just name and type without fields.

And separate 'FormFieldCollector' and 'FormFierldFinder' that collects `CollectedFormFields` (but without information about what Form it belongs to).

ANd then Resolver will create `Form` including `FormField`s from information from collected context data from finders.

**Comment by MartinMystikJonas** [comment]
So to summarise it:

`CollectedForm` - class, method, name, type
`CollectedFormField` - class, method, name, type

`Form` - name, type, form fields
`FormField` - name, type

`FormCollector` + `FormFinder` - collects forms created in class/method (without fields)
`FormFieldCollector` + `FormFieldFinder` - collected form fileds added to form in given method (without knowing to what form it is added)

`*Resolver` - gets all `CollectedForm` for given context, for each od then find all `CollectedFormField` (recursively) and combines it to create `Form` instances with `FormField` that is then passed to `Template`

**Comment by MartinMystikJonas** [comment]
Also I think we should somehow attempt to reduce errors for unresolved forms. Currently I get this for every unknown field of unresolved form.

```
/app/app/Components/Sign/templates/SignInForm.latte:8    ⇨  Form field with name "login" probably does not exist.
/app/app/Components/Sign/templates/SignInForm.latte:9    ⇨  Access to an undefined property Nette\ComponentModel\IComponent::$errors.
/app/app/Components/Sign/templates/SignInForm.latte:9    ⇨  Call to an undefined method Nette\ComponentModel\IComponent::hasErrors().
/app/app/Components/Sign/templates/SignInForm.latte:14   ⇨  Call to an undefined method Nette\ComponentModel\IComponent::hasErrors().
/app/app/Components/Sign/templates/SignInForm.latte:16   ⇨  Call to an undefined method Nette\ComponentModel\IComponent::getLabel().
```

Problem is that form is assigned like this in compiled template form `{form}`:

```php
$form = $this->global->formsStack[] = $this->global->uiControl['form'];
```

which probably set type based on acces to `uiControl` as `Nette\ComponentModel\IComponent`. I think we should maybe add visitor that would add `/** @var \Nette\Forms\Form */`

**Comment by lulco** [comment]
Please add test case(s) where Form is created and used by other then createComponent* way.

**Comment by lulco** [comment]
Forms and Fields are not all parts of Forms, we need also Groups and Containers (at least, analysis is not completed yet). For now I was thinking about ID for form (which will be somehow predictable - e.g. class name + method name where it is created?) and then maybe some new annotation for additional fields (containers, groups) which are added on some other places. All found items could be merged in Finder. I don't know why it should be in Resolver instead of Finder.

**Comment by lulco** [comment]
Errors like "Call to an undefined method Nette\ComponentModel\IComponent::hasErrors()." can be supressed for unknown fields of known forms if we use type BaseControl instead of IComponent in [Postprocessor](https://github.com/efabrica-team/phpstan-latte/blob/main/src/Compiler/Postprocessor.php#L118). For unknown forms we would have to add stubs for forms and override types which are defined in nette/forms and nette/component. Problem is that not all fields are BaseControls, only 99.9% ;)

**Comment by lulco** [comment]
code `$form = $this->global->formsStack[] = $this->global->uiControl['form'];` should never occure in compiled template if we find all forms

**Comment by MartinMystikJonas** [comment]
I will write some tests based on my use cases.

I will think about it bit more. True enough is that if we make finder smart enough and create some anotations it might be enough.

It was meant to reduce noise when form is not found for some reason. Now it produces hundreds of errors in my use cases and most of them are just noise.

**Comment by MartinMystikJonas** [comment]
I wrote some basic test cases. See #180

**Comment by lulco** [comment]
I think this is already implemented. If there is some missing part, create new issue

**Comment by MartinMystikJonas** [comment]
it is done
