### ISSUE TITLE
Class self was not found while trying to analyse it - discovering symbols is probably not configured properly.

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#145]
We got this error in real app when extension is active. It is not caused by rule becaus eerror occurs even without it. My guess it is somewhere in collectors but I need to investigate.

**Comment by lulco** [comment]
Maybe CalledClassResolver 

we have
```
if ($calledClassName === 'parent') {
```

but there is no check for other special names: see Name::$specialClassNames from PHP parser

**Comment by MartinMystikJonas** [comment]
Bingo! I will prepare PR with fix
