### ISSUE TITLE
Replace FileAnalyser with PHPStan exec + output parsing for analysing of compiled tempaltes

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#159]

**Comment by lulco** [comment]
To be honest, I don’t see the reason of this step. Analysis working as is. The problem was only with collecting data

**Comment by MartinMystikJonas** [comment]
Also I figured out that there would be some significant complications with this (we would need to detect and pass all original parameters). It was recommended by Ondrej to avoid potential BC breaks with FileAnalyser, but I think we can let this to be an issue after some significant BC break hits us.

**Comment by lulco** [comment]
Agree. We always can try to rewrite it using some internal methods. And if it will not be possible once, than we can call phpstan with exec.

can we close it?

**Comment by MartinMystikJonas** [comment]
Close it
