### ISSUE TITLE
Docs: result preview

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#164]
What about adding image with result preview to README? Like this:

[Preview](https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=seti&wt=none&l=text&width=680&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=------%2520------------------------------------------------------------------------------------------------%250A%2520Line%2520%2520%2520App%252FPresenters%252Ftemplates%252FUser.default.latte%2520rendered%2520from%2520App%255CPresenters%255CUserPresenter%253A%253Adefault%250A------%2520------------------------------------------------------------------------------------------------%2520%250A%2520%252030%2520%2520%2520%2520Variable%2520%2524record%2520might%2520not%2520be%2520defined.%250A%2520%252040%2520%2520%2520%2520Form%2520field%2520with%2520name%2520%2522form-submit%2522%2520probably%2520doesn%27t%2520exist.%250A%2520%252045%2520%2520%2520%2520Component%2520with%2520name%2520%2522datagrid%2522%2520probably%2520doesn%27t%2520exist.%250A%2520%252052%2520%2520%2520%2520Access%2520to%2520an%2520undefined%2520property%2520App%255CModel%255CEntity%255CUser%253A%253A%2524mail.%250A%2520%252060%2520%2520%2520%2520Undefined%2520latte%2520filter%2520%2522datetime%2522.%250A%2520%252065%2520%2520%2520%2520Parameter%2520%25231%2520%2524id%2520of%2520method%2520App%255CPresenters%255CUser%253A%253AactionEdit%28%29%2520expects%2520string%252C%2520null%2520given.%2520)

**Comment by lulco** [comment]
Yes! 👍
