### ISSUE TITLE
Links with additional parameters

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#198]
When you create link you can add additional parameter that are not part of action/render method. For example you can reference some parsistent parameter but parameter can be also loaded dynamically in action body using `->getParameter()`. Should we ignore additional parameters?

**Comment by lulco** [comment]
If we will ignore additional parameters, we can lost real errors or not?

**Comment by MartinMystikJonas** [comment]
In some cases yes. At least we should ignore any parameters with matching persistent parameter in target presenter. That is definetly not an error. For additional parameters I think we maybe should emit specific error something like "Unknown parameter ABC for XX::YY" that can be ignored

**Comment by lulco** [comment]
So we should collect persistent parameters, send them to LinkNodeProcessor and then ignore them if they are used in links as extra parameters?

can you prepare PR? I don’t use persistent parameters because I don’t like them from the first time is saw them :) so I really don’t know how it works.

**Comment by lulco** [comment]
We can close this issue. If it was only partially solved, we will create new one.

**Comment by MartinMystikJonas** [comment]
There is still issue that it is valid to  pass additional parameters ebcaise they can be read dynamically but it should have better error

**Comment by lulco** [comment]
We can't cover 100% :) Focus on main issues from our (my, your and spaze's) projects :) If somebody else will report issue which is relevant, we will try to fix it. Or recommend to ignore it 🤷

**Comment by lulco** [comment]
OK we failed to this issue :)

**Comment by lulco** [comment]
`{link Do:something, 'filter' => ['a' => 'b']}`

maybe we could skip named parameters which are not parameters of target method

**Comment by MartinMystikJonas** [comment]
Well either ignore it or show better error message that it is unknown parameter. When it is parameter not defined in method nor as persistent param there is no way to tell if it is typo in parameter or dynamic aprameter.

**Comment by lulco** [comment]
Nette is adding those parameters to url query. All of them. Regardless they are used (read dynamically) or not

**Comment by MartinMystikJonas** [comment]
so ignore it completely?

**Comment by lulco** [comment]
If it is named and not matched with method param than yes
