### ISSUE TITLE
Assign to dynamic template variable 

### ISSUE THREAD

**Issue by lulco** [efabrica-team/phpstan-latte#201]
$var = 'something';
$this->template->$var = 'value';

Should be evaluated as something variable sent to template.

this should work also if it is called in foreach

**Comment by lulco** [comment]
@MartinMystikJonas this is solved, right?

**Comment by MartinMystikJonas** [comment]
I think it is not.

**Comment by lulco** [comment]
is it even possible?

**Comment by MartinMystikJonas** [comment]
Yes. Just use value resolver resolveStrings to get possible names from expression in $node->var

**Comment by lulco** [comment]
I did it, null was returned :'(

**Comment by MartinMystikJonas** [comment]
Should work. Can you show me the code?

**Comment by lulco** [comment]
I've deleted it but it was like you say: ValueResolver-> resolveStrings($node->var); Maybe I scrawed something :D

**Comment by MartinMystikJonas** [comment]
Or maybe we have bug in vakue resolver. But it should work that way.
