### ISSUE TITLE
LattetEmplateResolver for templates without corresponding class

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#202]
Some templates do not have any corresponding class in app because their code is only in vendor. We need some way to write resolver that searches for such templates without need to bind to any Node.

REquested by @mabar

**Comment by lulco** [comment]
Solved by https://github.com/efabrica-team/phpstan-latte/pull/204, right? @MartinMystikJonas

**Comment by MartinMystikJonas** [comment]
Yes with #204 it sould be possible to write required resolver. After #206 and following changes for *Global trait is finalized I will write some basic tutorial how to make such resolver for @mabar use-case.
