### ISSUE TITLE
New nette/forms brokem forms visitor

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#219]
Generated code to get form field now looks like this:

```php
\Nette\Bridges\FormsLatte\Runtime::item('select', $this->global)
```

it does same thing as previous version

```php
$this->global->formsStack['select'];
```

We need to replace both versions with analysable reference to `$form`

**Comment by MartinMystikJonas** [comment]
@lulco: Can you look at it?

**Comment by lulco** [comment]
Yes, I'll try.

**Comment by lulco** [comment]
It's completely changed https://github.com/nette/forms/commit/e090ae5f63f16e544f5ae31f0fdcda61479490ba

Do we want to to support both versions or only this new one?

**Comment by MartinMystikJonas** [comment]
I would go for both because many people use older versions for various compatibility reasons.

**Comment by MartinMystikJonas** [comment]
For now maybe as quick fix add version constraint to composer.json to do not allow versions where it is changed? Better keep older version for some time than produce errors I think.

**Comment by lulco** [comment]
it doesn't matter what is in our composer.json, it is only in require-dev :)

**Comment by MartinMystikJonas** [comment]
We can add it to `conflict`

**Comment by lulco** [comment]
I have phpstan outside of app - globally installed, so this is not solution either

**Comment by MartinMystikJonas** [comment]
well it would fix it in CI at least

**Comment by lulco** [comment]
I'm almost done, just these errors need to fix:
```
+default.latte:50: Call to an undefined method object::getControl().
+default.latte:50: Parameter #1 (mixed) of echo cannot be converted to string.
+default.latte:52: Call to an undefined method object::getControl().
+default.latte:52: Parameter #1 (mixed) of echo cannot be converted to string.
```

it's because of this: ```public static function item($item, $global): object```

For variables we keep original code
```
echo \Nette\Bridges\FormsLatte\Runtime::item($name, $this->global)->getControl();
```
Any idea how to solve it?

**Comment by MartinMystikJonas** [comment]
Weel I think we should replace

```php
\Nette\Bridges\FormsLatte\Runtime::item($name, $this->global)
```

with 

```php
$form[$name]
```

If variable `$name` value is constant string it should be handled by PHPStan itself.

**Comment by lulco** [comment]
Well I did it but in that case I had another error:
```
+ default.latte:52: Offset Nette\Forms\Controls\TextArea does not exist on FirstForm_86ccb4a9d91fd89bcaf71ae19dd67fe1.
```

So I use this if from array dim fetch
```
} elseif ($node->dim instanceof Variable) {
    // dynamic field
}
```
