### ISSUE TITLE
Collect form fields added via method which is added by Container::extensionMethod

### ISSUE THREAD

**Issue by lulco** [efabrica-team/phpstan-latte#222]
Example:

Extension:
```

/**
 * @return SelectBox|HiddenField
 */
Container::extensionMethod('addAccount', function (Container $container, $name = 'account_id', $label = 'Account') {
    // register some field
});
```

Usage:
```
$form = new Form();
$form->addAccount();
```
This form should have one field with name account_id and type `SelectBox|HiddenField`.

Usage 2:
```
$form = new Form();
$form->addAccount('my_account_id');
```
This form should have one field with name `my_account_id` and type `SelectBox|HiddenField`.

Idea:
Collect extension methods, use them in FieldFinder when form call some method

**Comment by MartinMystikJonas** [comment]
I am not sure it would be possible. There are many ways how and where extension methods could be added. And PHPStan itself would report missing method there without correct `@method` annotation or stub.

In our code we simply add `@method` annotation with correct return type.

**Comment by lulco** [comment]
I have added @method for these additional methods. But it find just return type, not field name ;)

**Comment by MartinMystikJonas** [comment]
Now I see that in first case field name is ommited. I never seen such use. I guess we can collect default value

**Comment by MartinMystikJonas** [comment]
You would have to specify default in annotation

**Comment by lulco** [comment]
You can create your custom fields like you wish. Not always first argument is name - which reminds me we use always first argument in collector.
There are thousands usages of those fields, I will not add annotation there.

**Comment by MartinMystikJonas** [comment]
You do not need to add thousand annotations. Just creaste stub for form Container with correct annotation.

How can we detect which argument is field name?

**Comment by MartinMystikJonas** [comment]
I think we can go with assumption that firrst argument is field name and maybe create some config value to configure it for manually? I do not think there is a way to detect it automatically.

**Comment by lulco** [comment]
> You do not need to add thousand annotations. Just creaste stub for form Container with correct annotation.

Sorry here I get lost, what does it mean add stub form Container?
I have this:
```php
/**
 * @method SelectBox|HiddenField addAccount(string $name = 'account_id', string $label = 'Account')
 */
class Form extends NetteApplicationUiForm
{
}
```

> How can we detect which argument is field name?

I don't know, probably only check value of parameter "$name"?

**Comment by lulco** [comment]
> You do not need to add thousand annotations. Just creaste stub for form Container with correct annotation.

Ah, I thought that "annotation" means something like add something like `@phpstan-field-name` to all forms where ->addAccount() is used :D

**Comment by MartinMystikJonas** [comment]
That should be enough

**Comment by MartinMystikJonas** [comment]
Check #223

**Comment by lulco** [comment]
Resolved by https://github.com/efabrica-team/phpstan-latte/pull/223 and https://github.com/efabrica-team/phpstan-latte/pull/224
