### ISSUE TITLE
Method Nette\Forms\Controls\BaseControl::getControlPart() invoked with 1 parameter, 0 required.

### ISSUE THREAD

**Issue by lulco** [efabrica-team/phpstan-latte#225]
For checkbox and checkbox list there is parameter in getControlPart. The problem is if the checkbox / checkbox list is rendered as dynamic control. In that case it is marked as BaseControl.
Ignore this error or are we able to detect / fix it somehow?

**Comment by MartinMystikJonas** [comment]
I would ignore it.

**Comment by lulco** [comment]
globally here in extension? or let it to users?

**Comment by MartinMystikJonas** [comment]
Globally
