### ISSUE TITLE
Error: Unable to acquire exclusive lock

### ISSUE THREAD

**Issue by spaze** [efabrica-team/phpstan-latte#229]
I'm often (not always though) getting errors like

> Error: Efabrica\PHPStanLatte\LatteContext\Collector\NetteApplicationUIPresenterCollector error: Unable to acquire exclusive lock on file '/home/runner/work/michalspacek.cz/michalspacek.cz/site/app/Application/../../temp/cache/nette.robotLoader/321b52c2ae1136a4af15b7f7f03afa78.php.lock'. file_get_contents(/tmp/phpstan/michalspacek.cz-latte-templates/cache/nette.configurator/Container_d9b6d98fc7.php.meta): Failed to open stream: No such file or directory

Both when running in GitHub Actions ([example](https://github.com/spaze/michalspacek.cz/actions/runs/3896057532/jobs/6652122138#step:6:165)) and on my local.

**Comment by spaze** [comment]
"Important note - if you use robot loader, you will probably face the issue with lock “ Unable to acquire exclusive lock on file”. It’s because bootstrap is included more than once at the time. I had to “cache” it https://github.com/dev-efabrica/efabrica-phpstan-config/blob/phpstan-latte/includes/nette-app/bootstrap.php"

_Originally posted by @lulco in https://github.com/efabrica-team/phpstan-latte/issues/27#issuecomment-1379463079_

**Comment by MartinMystikJonas** [comment]
Any idea where we include it more than once? Could we prevent it?

**Comment by spaze** [comment]
> if you use robot loader

I think I can just stop using it :-)

**Comment by MartinMystikJonas** [comment]
I think I found root cause. I will try to fix it.

**Comment by lulco** [comment]
This is not issue with phpstan-latte, but phpstan (parallel execution) and robot loader.

You could try to fix it here:
https://github.com/spaze/michalspacek.cz/blob/spaze/phpstan-latte/site/app/PhpStan/latteEngine.php

using something like this https://github.com/dev-efabrica/efabrica-phpstan-config/blob/phpstan-latte/includes/nette-app/bootstrap.php

**Comment by MartinMystikJonas** [comment]
I think we can do similar thing in compilerFactory to require engineBootstrap.php only once. Or not?

**Comment by lulco** [comment]
Aah, you use it too, right? :) Yes, maybe we should... I use configuration setup :)

**Comment by MartinMystikJonas** [comment]
I use it too. I will make PR with fix. Lets see if it will help.

**Comment by MartinMystikJonas** [comment]
@spaze Can you test current main if it is resolved?

**Comment by spaze** [comment]
Thanks, I have meanwhile stopped using robot loader but if the error comes back I'll reopen the issue.
