### ISSUE TITLE
Documentation: add phpstan/phpstan-nette requirements

### ISSUE THREAD

**Issue by spaze** [efabrica-team/phpstan-latte#231]
These actions have no templates, so maybe these shouldn't be reported?

1. "26     Cannot resolve latte template for action default" [link](https://github.com/spaze/michalspacek.cz/actions/runs/3897378057/jobs/6654992072#step:6:51)
uses `redirect()`
https://github.com/spaze/michalspacek.cz/blob/71fd6075535830d05fe927ea9465e95acccb7133/site/app/Admin/Presenters/SignPresenter.php#L26-L29
"71     Cannot resolve latte template for action out" [link](https://github.com/spaze/michalspacek.cz/actions/runs/3897378057/jobs/6654992072#step:6:52)
https://github.com/spaze/michalspacek.cz/blob/71fd6075535830d05fe927ea9465e95acccb7133/site/app/Admin/Presenters/SignPresenter.php#L71-L77
both actions just redirect, but no error reported here
https://github.com/spaze/michalspacek.cz/blob/71fd6075535830d05fe927ea9465e95acccb7133/site/app/Admin/Presenters/SignPresenter.php#L32-L39 (also redirects)

2. " 23     Cannot resolve latte template for action default" [link](https://github.com/spaze/michalspacek.cz/actions/runs/3897378057/jobs/6654992072#step:6:112)
The method uses `sendJson()`:
https://github.com/spaze/michalspacek.cz/blob/71fd6075535830d05fe927ea9465e95acccb7133/site/app/Api/Presenters/ErrorPresenter.php#L23

3. "19     Cannot resolve latte template for action default" [link](https://github.com/spaze/michalspacek.cz/actions/runs/3897378057/jobs/6654992072#step:6:118)
Uses `sendResponse()`:
https://github.com/spaze/michalspacek.cz/blob/71fd6075535830d05fe927ea9465e95acccb7133/site/app/Pulse/Presenters/ErrorPresenter.php#L21

4. "22     Cannot resolve latte template for action storagesQuestions" [link](https://github.com/spaze/michalspacek.cz/actions/runs/3897378057/jobs/6654992072#step:6:125) + "33     Cannot resolve latte template for action storagesRating" [link](https://github.com/spaze/michalspacek.cz/actions/runs/3897378057/jobs/6654992072#step:6:126)
Both actions use `redirectPermanent()`
https://github.com/spaze/michalspacek.cz/blob/71fd6075535830d05fe927ea9465e95acccb7133/site/app/Pulse/Presenters/PasswordsPresenter.php#L24

**Comment by lulco** [comment]
Do you have phpstan-nette extension? I think this is config which is used to supress those errors: https://github.com/efabrica-team/phpstan-latte/blob/main/tests/config.neon#L9

**Comment by spaze** [comment]
Oh, nice, thanks. I had phpstan-nette loaded in the other `phpstan.neon` but not in the one that does phpstan-latte checks. Do you think the requirement should be documented in the Installation section? And maybe even have `phpstan/phpstan-nette` in `require` in `composer.json`?

**Comment by lulco** [comment]
I was thinking about it too. It definitelly should be in docs. I am not sure about composer, because you have to add it to your phpstan config anyways, right?

**Comment by lulco** [comment]
Hm, it seems method redirectPermanent is missing in phpstan extension. 

https://github.com/phpstan/phpstan-nette/blob/1.1.x/extension.neon#L31

**Comment by spaze** [comment]
> I am not sure about composer, because you have to add it to your phpstan config anyways, right?

Sure, but adding it to `composer.json` too would allow the docs to have one manual step less :-) Unless there's a situation where you may not need phpstan-nette.

**Comment by spaze** [comment]
> Hm, it seems method redirectPermanent is missing in phpstan extension.
> 
> https://github.com/phpstan/phpstan-nette/blob/1.1.x/extension.neon#L31

And I thought I've already hit the issue and added it :| PR'd it now https://github.com/phpstan/phpstan-nette/pull/113

**Comment by spaze** [comment]
Oh, I thought... and I actually did, that's why it rang a bell. But the fix was in Nette, still pending release https://github.com/phpstan/phpstan-nette/pull/79#issuecomment-1152794607 + https://github.com/nette/application/pull/304

**Comment by lulco** [comment]
I think `never` return typehint shouldn’t be precondition to add method to `earlyterminatingmethodcalls`. Still, you can add it in your app until it will be in phpstan-nette

**Comment by spaze** [comment]
I think it's more of *the* fix than a precondition for adding but yeah, I have it in my config for like half a year, since at least creating the PR, with a note to remove it.

**Comment by spaze** [comment]
And the `return never` tag has now been released in nette/application 3.1.10 (but the extension doesn't seem to care much, see #261)
