### ISSUE TITLE
"Presenter::actionWithParametersMissingCorrespondingMethod not found"

### ISSUE THREAD

**Issue by spaze** [efabrica-team/phpstan-latte#233]
@spaze can you please paste compiled code for this template Admin/Presenters/templates/Talks/default.latte  ? 

Error should be different and transformed to more readable version.

```
 ------ ----------------------------------------------------------------------- 
  Line   Admin/Presenters/templates/Talks/default.latte rendered from           
         MichalSpacekCz\Admin\Presenters\InterviewsPresenter::interview         
         included in Admin/Presenters/templates/Interviews/default.latte        
         included in Admin/Presenters/templates/Interviews/interview.latte      
 ------ ----------------------------------------------------------------------- 
  -1     Method                                                                 
         MichalSpacekCz\Admin\Presenters\InterviewsPresenter::slidesWithParame  
         tersMissingCorrespondingMethod not found                               
 ------ ----------------------------------------------------------------------- 
```
([Link to the error in workflow run](https://github.com/spaze/michalspacek.cz/actions/runs/3897801662/jobs/6655848292#step:6:54))

_Originally posted by @lulco in https://github.com/efabrica-team/phpstan-latte/issues/193#issuecomment-1379648081_

**Comment by spaze** [comment]
> @spaze can you please paste compiled code for this template Admin/Presenters/templates/Talks/default.latte ?
> 
> Error should be different and transformed to more readable version.

Yeah, that's indeed an interesting error :-) Here you go https://gist.github.com/spaze/ae214b8c1f1e5ba5816889d09e09cf80

**Comment by lulco** [comment]
Sorry I ment compiled and transformed by our extension. It should be in /tmp folder if you didn’t change it. See https://github.com/efabrica-team/phpstan-latte/blob/main/tests/config.neon#L3

You can use tmp or temp as the value and files will be stored in your application for easier debugging

**Comment by spaze** [comment]
Ah, sorry, https://gist.github.com/spaze/ae214b8c1f1e5ba5816889d09e09cf80 updated with hopefully the right files.

**Comment by lulco** [comment]
@spaze see https://github.com/efabrica-team/phpstan-latte/pull/248, we think you should rework that template :) easy fix is to add Presenter to links

**Comment by spaze** [comment]
Thanks, I have extracted the common part.
