### ISSUE TITLE
Add a line about PHPStan levels to docs

### ISSUE THREAD

**Issue by spaze** [efabrica-team/phpstan-latte#239]
I'm running phpstan-latte with a different separate PHPStan config so I can test templates in parallel with running "regular" PHPStan (which runs much faster). And the config file has `customRulesetUsed: true` and no level specified which essentially means PHPStan is using level 0 - which means that possibly undefined variables are not reported.

I think it would be nice to add a line or two to docs saying that maybe you want to run PHPStan with rule level at least 1 :-) I'll now increase the level in my own config and see what I need to do and fix.

_Originally posted by @spaze in https://github.com/efabrica-team/phpstan-latte/issues/193#issuecomment-1380746804_

**Comment by lulco** [comment]
Well it uses the same config as for php :) same rules at same levels

**Comment by lulco** [comment]
We can mention it in docs

**Comment by spaze** [comment]
I incorrectly assumed that unknown variables and actually everything in the template would be checked by this extension but as they say... https://youtu.be/wg4trPZFUwc

**Comment by lulco** [comment]
Well, no :) this extension just (simplified saying) creates php from latte templates and analyse them with all available rules you have turned on in your config

**Comment by spaze** [comment]
I know now, that's why the past tense :-) But I think what you just said is clear enough and could also be copied tom the docs 👍
