### ISSUE TITLE
Need to have `redirectPermanent` in `earlyTerminatingMethodCalls`

### ISSUE THREAD

**Issue by spaze** [efabrica-team/phpstan-latte#261]
I'm using phpstan/phpstan-nette 1.2.1, nette/application 3.1.10, phpstan-latte 0.4.0.

My action uses `redirectPermanent()`:

```php
	public function actionStoragesQuestions(): never
	{
		$this->redirectPermanent('PasswordsStorages:questions');
	}

```

The phpstan-latte extensions says
```
 ------ ------------------------------------------------------------ 
  Line   Pulse/Presenters/PasswordsPresenter.php                     
 ------ ------------------------------------------------------------ 
  22     Cannot resolve latte template for action storagesQuestions  
  33     Cannot resolve latte template for action storagesRating     
 ------ ------------------------------------------------------------ 
```

even though `redirectPermanent` has `return never`:
```php
	/**
	 * Permanently redirects to presenter, action or signal.
	 * @param  string   $destination in format "[//] [[[module:]presenter:]action | signal! | this] [#fragment]"
	 * @param  array|mixed  $args
	 * @return never
	 * @throws Nette\Application\AbortException
	 */
	public function redirectPermanent(string $destination, $args = []): void
	{
```

To get rid of those "Cannot resolve latte template" errors, I need to add this to my `phpstan.neon` config:

```neon
earlyTerminatingMethodCalls:
		Nette\Application\UI\Component:
			- redirectPermanent
```

It's not needed for "normal" PHPStan anymore (starting with nette/application 3.1.10) but phpstan-latte still requires it.

Can the extension check the return type hint too?

**Comment by MartinMystikJonas** [comment]
This is a bit dilemma now because we do not have reliable way to detect always/sometimes called methods and especially in deeper call trees. So any never method user for example to throw exception somewhere in call tree would disable reposting of unresolved template.

I was planning to add support for any never method call later when this is resolved to avoid hiding real errors.

**Comment by spaze** [comment]
Would adding something like "|| has return never" to the "is earlyTerminatingCall" condition somewhere around here help? https://github.com/efabrica-team/phpstan-latte/blob/f7fd8d02e4736f67a309146451f1b58ffc529ccf/src/Resolver/CallResolver/TerminatingCallResolver.php#L66

**Comment by MartinMystikJonas** [comment]
Yes that would be a way to implement it
