### ISSUE TITLE
exit(); is not evaluated as early terminating call

### ISSUE THREAD

**Issue by lulco** [efabrica-team/phpstan-latte#291]
I have Presenter with action like:

```php
public function actionCopy(string $id): void
{
    // do something
    print $id;
    exit();
}
```

There is no template for this action obviously, but I've got error `Cannot resolve latte template for action copy`

**Comment by MartinMystikJonas** [comment]
Why you do not use `$this->terminate()` ? 

I will add exit to nodes detected as terminating calls

**Comment by lulco** [comment]
Failing test cases added https://github.com/efabrica-team/phpstan-latte/pull/292

**Comment by lulco** [comment]
> Why you do not use `$this->terminate()` ?

Not my code, it's something legacy, but valid.
