### ISSUE TITLE
Call to function is_object() with string will always evaluate to false.

### ISSUE THREAD

**Issue by lulco** [efabrica-team/phpstan-latte#293]
Code in latte:
```latte
{foreach $foo as $bar}
    {control $bar}
{/foreach}
```

leads to compiled template like this:
```php
foreach ($foo as $bar) {
    if (\is_object($bar)) {
        $_tmp = $bar;
    } else {
        $_tmp = $this->global->uiControl->getComponent($bar);
    }
    if ($_tmp instanceof \Nette\Application\UI\Renderable) {
        $_tmp->redrawControl(\null, \false);
    }
    $_tmp->render();
    $iterations++;
}
```

and it leads to error:
`Call to function is_object() with string will always evaluate to false.`
or
`Call to function is_object() with object will always evaluate to true.`

It's because this line in UIMacros::macroControl:
```php
($name[0] === '$' ? "if (is_object($name)) \$_tmp = $name; else " : '')
```
All dynamic control names are check if they are not already an object.

Any idea how we could fix this? Or would we just ignore this condition?

**Comment by lulco** [comment]
This is another use case when scope in node visitor would be handful.

**Comment by MartinMystikJonas** [comment]
Well I would preffer to keep it using just nodes if possible.

I would add `@phpstan-ignore-next-line` to If node when
- condition expr contains `is_object` FuncCall
- first stmt in true branch is `Assign` to `$_tmp` or `$L_tmp` (with that weird L)

**Comment by lulco** [comment]
Yes, that's also solution, I'm just afraid we will suppress some real errors

**Comment by MartinMystikJonas** [comment]
I d not think there is a chance this would match any not-relevant code where we want to keep errors
