### ISSUE TITLE
Filters with FilterInfo

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#296]
Latte filters can be defined with FilterInfo as first parameter (it is automatically added by FilterExecutor)

```php
public function markdown(FilterInfo $info, $text) {
```

But when we replace filtrs with methods we do not add it. When called filter first argument is of type FilterInfo we should pass it.

**Comment by lulco** [comment]
There are special filters in node visitor https://github.com/efabrica-team/phpstan-latte/blob/main/src/Compiler/NodeVisitor/ChangeFiltersNodeVisitor.php#L196, just add markdown to them. Is it built-in filter? Or should we open this list to outside developers?

**Comment by MartinMystikJonas** [comment]
It is our custom filter. I just encountered when I added latte analysis to another of our projects. It should be autodetected from filter signature.

**Comment by lulco** [comment]
Yes it should. I even didn’t know that filter can say that it needs FilterInfo 🤷‍♂️

**Comment by lulco** [comment]
Will you implement it?

**Comment by lulco** [comment]
Here is code from nette to detect if first parameter is of type FilterInfo:
```php
$ref = is_array($callback)
    ? new \ReflectionMethod($callback[0], $callback[1])
    : new \ReflectionFunction($callback);
$this->_static[$name][1] = ($tmp = $ref->getParameters())
    && $tmp[0]->getType() instanceof \ReflectionNamedType 
    && $tmp[0]->getType()->getName() === FilterInfo::class;
```

**Comment by MartinMystikJonas** [comment]
I will
