### ISSUE TITLE
Method Latte\Runtime\Filters::breaklines() has invalid return type Latte\Runtime\Html.

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#308]
in efabrica/phpstan-latte/stubs/Latte/Runtime/Filters.stub:96

**Comment by lulco** [comment]
what's wrong? https://github.com/nette/latte/blob/v2.11/src/Latte/Runtime/Filters.php#L550
do you have dev-main?

**Comment by MartinMystikJonas** [comment]
When you use any class in stubs you have to create stub for that class too.

**Comment by lulco** [comment]
we have Html stub https://github.com/efabrica-team/phpstan-latte/blob/main/stubs/Latte/Runtime/Html.stub
