### ISSUE TITLE
Add support for var, default and define macros

### ISSUE THREAD

**Issue by lulco** [efabrica-team/phpstan-latte#329]
If possible use also their types defined

**Comment by lulco** [comment]
It seems we removed all extract calls but one of them is used for default maybe also for var

**Comment by lulco** [comment]
Maybe this is related comment https://github.com/efabrica-team/phpstan-latte/blob/main/src/Compiler/NodeVisitor/RemoveExtractParamsNodeVisitor.php#L35

**Comment by MartinMystikJonas** [comment]
It will be possible by redefining these macros. Version for var could be based on implemwntation i did for latte itself in unaccepted PR. For other it should be similar.

I shoukd have a bit more time now so I can look at it.

**Comment by lulco** [comment]
Maybe they are different. I think default is compiled as extract (but we remove all extract calls as mentioned above), var is just for plugin so it is ok it is not in compiled template

**Comment by MartinMystikJonas** [comment]
We need to redefine these tags/macros if we want to propagate type information. It is ignored by default Latte implementation

**Comment by lulco** [comment]
`default` is not ignored, it puts extract function to compiled php code, we just use to remove it. I'm fixing it in #332
