### ISSUE TITLE
Template with `{form $form` throws "Ternary operator condition is always false."

### ISSUE THREAD

**Issue by spaze** [efabrica-team/phpstan-latte#388]
I have a template with ([source](https://github.com/spaze/michalspacek.cz/blob/82d0b7221e2b4251626acea8fbff3563991cbee0/site/app/Admin/Presenters/templates/Blog/common/postForm.latte#L1C1-L1C1))
```
{form $form class => "aligned wide blocking"}
```

That template is included in another template with ([source](https://github.com/spaze/michalspacek.cz/blob/82d0b7221e2b4251626acea8fbff3563991cbee0/site/app/Admin/Presenters/templates/Blog/add.latte#L8)):
```
{include "common/postForm.latte", form: addPost}
```
But the fact that it's an included template doesn't matter. It also happens when it's a top-level template with `{form $formName}` and the presenter does `$this->template->formName = 'invoice';`

The template is compiled to
```php
         /* line 1 */
        $form = $this->global->formsStack[] = \is_object($ʟ_tmp = $form) ? $ʟ_tmp : $this->global->uiControl[$ʟ_tmp];
```

Analyzing it on level 4 gives:
```
 ------ ---------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Compiled   Admin/Presenters/templates/Blog/common/postForm.latte rendered from MichalSpacekCz\Admin\Presenters\BlogPresenter::add included in Admin/Presenters/templates/Blog/add.latte
         line       See compiled template: /tmp/phpstan-latte/app/Admin/Presenters/templates/Blog/common/postForm.latte.5dfda1a7df692b7ec28925763179a399.php
 ------ ---------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  1      53         Ternary operator condition is always false.
 ------ ---------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

I don't know what to do with that :-(

**Comment by lulco** [comment]
Includes are not covered very well :( personally, I don’t use them much, so we have to look at them closely. Would be very helpful if you could create failing test cases

**Comment by spaze** [comment]
Thanks though it seems the issue is also present when the template is a top-level one and not included. I've updated the description.

**Comment by lulco** [comment]
I see, this is because of dynamic form name (variable is used here). I will check if we know the value of variable at the point when we are processing forms, because phpstan knows it later.
