### ISSUE TITLE
Variable in template used in two actions is true once, false then

### ISSUE THREAD

**Issue by spaze** [efabrica-team/phpstan-latte#390]
I have a template ([source](https://github.com/spaze/michalspacek.cz/blob/82d0b7221e2b4251626acea8fbff3563991cbee0/site/app/Pulse/Presenters/templates/PasswordsStorages/default.latte#L5)) with:
```html
{if $isDetail}&raquo; <a n:href="default">Passwords storages</a>{/if}
```
The template is used in two actions:
1. in `actionDefault` ([source](https://github.com/spaze/michalspacek.cz/blob/82d0b7221e2b4251626acea8fbff3563991cbee0/site/app/Pulse/Presenters/PasswordsStoragesPresenter.php#L32))
2. in `actionSite` ([source](https://github.com/spaze/michalspacek.cz/blob/82d0b7221e2b4251626acea8fbff3563991cbee0/site/app/Pulse/Presenters/PasswordsStoragesPresenter.php#L59)) by calling `$this->setView('default');`
The template is compiled to `if ($isDetail) {` in both cases.

However, analysis shows this in the first case::
```
------ ---------- -----------------------------------------------------------------------------------------------------------------------------------------------
  Line   Compiled   Pulse/Presenters/templates/PasswordsStorages/default.latte rendered from MichalSpacekCz\Pulse\Presenters\PasswordsStoragesPresenter::default
         line       See compiled template: /tmp/phpstan-latte/app/Pulse/Presenters/templates/PasswordsStorages/default.latte.b6bb0c039f77aca94a2c1dc7262492e8.php
 ------ ---------- -----------------------------------------------------------------------------------------------------------------------------------------------
  5      156        If condition is always false.
```

while in the second case:
```
 ------ ---------- ----------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Compiled   Pulse/Presenters/templates/PasswordsStorages/default.latte rendered from MichalSpacekCz\Pulse\Presenters\PasswordsStoragesPresenter::site(default)
         line       See compiled template: /tmp/phpstan-latte/app/Pulse/Presenters/templates/PasswordsStorages/default.latte.22e164e6fbd05dd3f83a6626b12ada11.php
 ------ ---------- ----------------------------------------------------------------------------------------------------------------------------------------------------
  5      156        If condition is always true.
```

I'm not sure if I can do something with it, please help.

**Comment by lulco** [comment]
Hi, yes this is known "issue". It is kind of documented [here](https://github.com/efabrica-team/phpstan-latte/blob/main/docs/how_it_works.md) . It is all about the context which is collected only for one action at the time. Also it is caused be precise types of variables (true/false instead of bool).

The same problem rises when you use defaults in template.

 I'm thinking about some config switch where you can set if types should be more or less precise. But that will change some other behavior :)

**Comment by spaze** [comment]
Thanks, what do you think would be the best way to "fix" the "issue" on my side? Always happy to do things differently even if just because of the static analysis 😀

**Comment by lulco** [comment]
One way might be to change type from false to bool. So something like this should work.

Change:
```
$this->template->isDetail = false;
```
To:
```
$this->template->isDetail = $this->isDetail();

private function isDetail(): bool
{
    return false;
}
```

or some variable / property with bool type instead of method.

**Comment by spaze** [comment]
I see, thanks. Unfortunately it's the same presenter 🤣 so can't use neither a simple method nor a property but I get the point that I need "to change type from false to bool."

**Comment by lulco** [comment]
Then you can use:
```
$this->template->isDetail = $this->isDetail(false);

private function isDetail(bool $isDetail): bool
{
    return $isDetail;
}
```

I know, it’s kind of stupid :)

**Comment by spaze** [comment]
"If it's stupid but it works it ain't stupid." But this kinda is, indeed 🤣

I have a method like
```php
function setViewAndVars(bool $isDetail)
{
  $this->template->isDetail = $isDetail;
  // Set some more variables and then call setView()
}
```
It was already there and was setting some other variables so I have just extended it a bit to do this as well.

**Comment by spaze** [comment]
I think this can actually be closed now, don't think it requires any code changes (except on my side 😅). I've added some specific examples to documentation in #392 to help others in a similar situation.

**Comment by MartinMystikJonas** [comment]
You can also use `/** @phpstan-latte-var bool $isDetail*/` above assignment - this overwrites implicitly detected type
