### ISSUE TITLE
Form containers with numeric name

### ISSUE THREAD

**Issue by spaze** [efabrica-team/phpstan-latte#396]
First, I know that form containers may not be fully supported yet, see #380, but this may or may not be directly related so I'm still filing this.

I have a form with multiple containers (they're nested but that's unrelated I think)

This is how I build the containers, notice the `for` loop and `addContainer($i)`:
```php
		$disclosureNewContainer = $disclosureContainer->addContainer('new');
		for ($i = 0; $i < $newDisclosures; $i++) {
			$disclosureNewCountContainer = $disclosureNewContainer->addContainer($i);
```

In a template:
```latte
	{formContainer new}
		{formContainer $i}  <-- line 85
```

This is how it's compiled by the extension:
```
             /* line 84 */
            $this->global->formsStack[] = $formContainer = $form['new'];
            /* line 85 */
            $this->global->formsStack[] = $formContainer = \Nette\Bridges\FormsLatte\Runtime::item($i, $this->global);
```

I get this error on level 5:
```
 ------ ---------- ---------------------------------------------------------------------------------------------------------------------------------------------
  Line   Compiled   Admin/Presenters/templates/Pulse/passwordsStorages.latte rendered from MichalSpacekCz\Admin\Presenters\PulsePresenter::passwordsStorages
         line       See compiled template: /tmp/phpstan-latte/app/Admin/Presenters/templates/Pulse/passwordsStorages.latte.8f4b78add10adffe699f7ad521d7e14e.php
 ------ ---------- ---------------------------------------------------------------------------------------------------------------------------------------------
  85     437        Parameter #1 $item of static method Nette\Bridges\FormsLatte\Runtime::item() expects object|string, int<0, 2> given.
 ------ ---------- ---------------------------------------------------------------------------------------------------------------------------------------------
```

I'm not sure where `object|string` is coming from, because `\Nette\Bridges\FormsLatte\Runtime::item($item, $global): object` doesn't use any type declarations at all: https://github.com/nette/forms/blob/8a23250f05443cae8b7c8294003c3f2a9d38ffc5/src/Bridges/FormsLatte/Runtime.php#L115

And eventually does this
```php
return $form[$item];
```

**Comment by lulco** [comment]
This is partially solved in https://github.com/efabrica-team/phpstan-latte/pull/379/files

I changed all keys to string there. But dynamic values are not converted.


The object|string comes from our stub:

https://github.com/efabrica-team/phpstan-latte/blob/main/stubs/Nette/Bridges/FormsLatte/Runtime.stub

Maybe in this case we should just add int to this stub. I can prepare branch and you can try it.

**Comment by spaze** [comment]
Ha! I checked the phpstan-nette extension stubs but of course couldn't find anything, because this extension has its own stubs of course 😅 Thanks, will try to remember to check those as well next time 😊

Thanks for the branch, checking it now.
