### ISSUE TITLE
`{capture $link}Foo:bar{/capture}` throws "link() expects string" on level 7

### ISSUE THREAD

**Issue by spaze** [efabrica-team/phpstan-latte#398]
This is something I'm not sure is a bug, or something that can be fixed or changed in phpstan-latte but you tell me.

My template contains this:
```latte
<p class="separated">
	{capture $link}Trainings:application#{_html.id.application}{/capture}
	<a n:href="$link $name">{_messages.trainings.addanother}</a>  <-- line 54
```
which can probably be minimized to just:
```latte
{capture $link}Foo:bar{/capture}
<a n:href="$link">something</a>
```

and I get this:
```
 ------ ---------- -------------------------------------------------------------------------------------------------------------------------------------
  Line   Compiled   Www/Presenters/templates/Trainings/success.latte rendered from MichalSpacekCz\Www\Presenters\TrainingsPresenter::success
         line       See compiled template: /tmp/phpstan-latte/app/Www/Presenters/templates/Trainings/success.latte.accbee637de3e9eee62368a83384f885.php
 ------ ---------- -------------------------------------------------------------------------------------------------------------------------------------
  54     470        Parameter #1 $destination of method Nette\Application\UI\Component::link() expects string, Latte\Runtime\Html|string|false given.
 ------ ---------- -------------------------------------------------------------------------------------------------------------------------------------
```

The compiled code looks like this
```php
<p class="separated">
		';
        /* line 53 */
        \ob_start(fn() => '');
        try {
            echo 'Trainings:application#';
            /* line 53 */
            echo \Latte\Runtime\Filters::escapeHtmlText($__filter__translate->translate('html.id.application'));
        } finally {
            $ʟ_tmp = \ob_get_length() ? new \Latte\Runtime\Html(\ob_get_clean()) : \ob_get_clean();
        }
        $ʟ_fi = new \Latte\Runtime\FilterInfo('html');
        $link = $ʟ_tmp;
        echo '
		<a href="';
        /* line 54 */
        echo \Latte\Runtime\Filters::escapeHtmlAttr($this->global->uiControl->link($link, [$name]));  // line <- 470
        echo '">';
        /* line 54 */
        echo \Latte\Runtime\Filters::escapeHtmlText($__filter__translate->translate('messages.trainings.addanother'));
        echo '</a>
```
now the error seems more or less correct because of these lines
```php
$ʟ_tmp = \ob_get_length() ? new \Latte\Runtime\Html(\ob_get_clean()) : \ob_get_clean();
...
$link = $ʟ_tmp;
...
$this->global->uiControl->link($link, [$name]);
```
So in theory `$ʟ_tmp` can indeed be `new \Latte\Runtime\Html(\ob_get_clean())` or a result of `\ob_get_clean();` which is a string or false.

But, is there something I can do with that? I can change it to something like
```html
<a href="{link Trainings:training $name}#{_html.id.application}">
```
and the error will disappear but the original code seems to be a legal (and working) Latte expression.

**Comment by lulco** [comment]
So problem is only false? Not Latte\Runtime\Html?

Well we can transform the compiled code.
Replace \ob_get_clean(); with \ob_get_clean() ?: '';
Not sure if it is completelly correct because maybe we will hide some real bugs (I don’t know if it is true).

**Comment by lulco** [comment]
With strict types enabled for Engine your code will even not work.

https://github.com/nette/latte/blob/master/tests/common/Engine.strictTypes.phpt

Maybe you should cast capture output to string? Or not using capture at all here.

**Comment by spaze** [comment]
This is one of the bugs where I don't know where the problem is and who should fix it. You're correct that with strict types it won't work and that casting to string would fix it.

**Comment by lulco** [comment]
I think this is not the bug of phpstan-latte extension. I would rather say it is possible bug found by it :)

**Comment by spaze** [comment]
A possible bug where though? 😅

**Comment by lulco** [comment]
In your code O:-) and also it is weird that capture returns Html and not string :) I think it is not some public knowledge

**Comment by spaze** [comment]
It's not even documented I can't use a captured variable for links or that I have to type-cast it to string.

**Comment by lulco** [comment]
Maybe we should check the original compiled template :)) but I don’t think it is added by our extension.

Also maybe it is not documented because it works - Html is automatically casted thanks to non-strict template classes.

Then it is wrong phpstan behavior? Should it use Stringable classes / classes containing __toString() as strings?

**Comment by spaze** [comment]
I've checked the original Latte-compiled template and the code is basically the same.

It could also be Latte, it could cast whatever comes to link() for example to strings. Or document that what I was doing is not supported. Or throw an exception.

This is one of the things I'm not sure what's wrong and where. I could just write that part in a different way (and I've already done that) and be done with it but that doesn't help the thing (we just don't know which one) get better.

**Comment by dg** [comment]
You're capturing HTML and pasting it into the place where plain text is expected, so it doesn't work. 

It could be done like this:

```latte
{if}
<script type="text/plain">
    {capture $link}Foo:bar{/capture}
</script>
{/if false}
```

Then `$link` would be plain text stored in a string. But it's not a very nice solution.

**Comment by spaze** [comment]
> You're capturing HTML and pasting it into the place where plain text is expected, so it doesn't work.

It actually works (the template compiles just fine and works as expected), and I understand why, but PHPStan Latte says it doesn't, which I also understand why. But the difference is why I've filed the bug in the first place :-)

I've already found a nice solution: I've stopped using `{capture}` output for links :-)
