### ISSUE TITLE
Passing objects to filters like `lower` not detected

### ISSUE THREAD

**Issue by spaze** [efabrica-team/phpstan-latte#430]
I have [changed](https://github.com/spaze/michalspacek.cz/commit/bb47d701e3daf743a1e78d8454b24a888bd7e22a) a method (`getRating()` below) to return an object with a `value` property instead of a string:

```diff
- <strong class="right rating-{$site->getRating()|lower}"
+ <strong class="right rating-{$site->getRating()->name|lower}"
```

But forgot to do it in one of the places. The bug got to production undetected and started throwing exceptions about a string being required in the [`lower` filter](https://latte.nette.org/en/filters#toc-lower).

It would be cool if it was detected however I'm not sure how doable it is because the `lower` filter doesn't enforce/mention any types in the signature or docblock ([source](https://github.com/nette/latte/blob/cab0aceb8ed35917e9ac2565baa7989b5de5520c/src/Latte/Essential/Filters.php#L321-L327)):

```php
	/**
	 * Convert to lower case.
	 */
	public static function lower($s): string
	{
		return mb_strtolower((string) $s, 'UTF-8');
	}
```

But effectively it enforces `Stringable` for objects due to the type cast. And as with some of my previous bugs, I'm not sure that this extension is the right place to do it but I think this or very similar bug has already reached my prod once before 😅 so it would be cool if this could be detected.

Could this be done somehow?

**Comment by MartinMystikJonas** [comment]
Ideally this shoukd be solved directly in latte. But I think we can do it in stubs too

**Comment by lulco** [comment]
I’m pretty sure I’ve done stubs for all filters which accept string/stringable values. `lower` is covered here: https://github.com/efabrica-team/phpstan-latte/blob/edd43bcbc321808ba45b064031f4f51cc954a8ee/stubs/Latte/Runtime/Filters.stub#L117

**Comment by lulco** [comment]
It is correctly reported with latte 2.x https://github.com/efabrica-team/phpstan-latte/actions/runs/5883008492/job/15954740031#step:5:44
But not with latte 3.x :( I have to find the reason

**Comment by spaze** [comment]
Tried to minimize my code in https://github.com/spaze/michalspacek.cz/pull/199 and it's not detected, check the [very last error](https://github.com/spaze/michalspacek.cz/actions/runs/5882994632/job/15954697085?pr=199#step:6:84), it only mentions $foobar which is there to see the template has been analyzed. The other errors are the result of the imperfect minimization because the variables are not defined in respective actions.

**Comment by lulco** [comment]
@spaze can you confirm that branch [lower-on-object](https://github.com/efabrica-team/phpstan-latte/tree/lower-on-object) works?

**Comment by lulco** [comment]
The reason was missing stubs for Latte\Essential\Filters which is the new name of Filters class (previously Latte\Runtime\Filters). I hope I've covered all missing methods so this bug shouldn't happen with latte 3.x and with any filter

**Comment by spaze** [comment]
Oh, nice, that's so easy to miss! I know about the namespace change but didn't notice it even when you said you've added it and provided a link to the stub file which clearly says "Latte/Runtime/Filters.stub" 😅

I can confirm [lower-on-object](https://github.com/efabrica-team/phpstan-latte/tree/lower-on-object) pr #431 works ([log](https://github.com/spaze/michalspacek.cz/actions/runs/5884377923/job/15958986338?pr=199#step:6:63)) now:

```
  2      34         Parameter #1 $s of static method Latte\Essential\Filters::lower()                                                                                     
                    expects bool|float|int|string|Stringable|null,                                                                                                        
                    MichalSpacekCz\Pulse\Passwords\RatingGrade::B given. 
```

Thank you for the quick fix, hopefully no more of these bugs-in-prod for me 🥳
