### ISSUE TITLE
Standalone presenter action template is not analysed if presenter dir and template dir are siblings

### ISSUE THREAD

**Issue by lulco** [efabrica-team/phpstan-latte#442]

**Comment by MartinMystikJonas** [comment]
Does this even work in Nette? I think action templates should be in same folder as presenter or in templates sub-folder. Or does it work for different locations too?

**Comment by lulco** [comment]
I have project with structure:
```
presenters
  FooPresenter.php
templates
  Foo
    add.latte
    default.latte
```

and it seems working. I have to check if this is standard way in nette

**Comment by lulco** [comment]
I think this code block is responsible for it:
 ```
 $dir = is_dir("$dir/templates") ? $dir : dirname($dir);

        $templateFileCandidates = [
            $dir . '/templates/' . $presenterName . '/' . $actionName . '.latte',
            $dir . '/templates/' . $presenterName . '.' . $actionName . '.latte',
        ];

```
This is from our extension but I copied it from Nette.

**Comment by lulco** [comment]
https://github.com/nette/application/blob/40977525fa022c65cbe582f18ad0b12e9ad34dfb/src/Application/UI/Presenter.php#L545
