### ISSUE TITLE
Prevent recursion in MethodCallFinder

### ISSUE THREAD

**Issue by lulco** [efabrica-team/phpstan-latte#53]

**Comment by MartinMystikJonas** [comment]
@lulco I will make PR for this (after you merge that circular reference PR)

**Comment by MartinMystikJonas** [comment]
Check https://github.com/efabrica-team/phpstan-latte/pull/54 I did di right away when I was already messing with Finders in cache fix

**Comment by lulco** [comment]
Fixed by #55
