### ISSUE TITLE
Closure filters

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#57]
Support for checking filters added as closures. Would require adding fictional method to template with same signature as closure and replacing filter calls with calls to this method.

**Comment by lulco** [comment]
We don't need real methods, just their stubs. We can do:
- abstract methods (class have to be abstract too)
- add `__call()` and @method to class comments

**Comment by MartinMystikJonas** [comment]
Or maybe just add:
```
  /** @var callable(string, int): string
  private $__filter_xyz;
```
```
  $this->__filter__xyz($a, $b);
```
