### ISSUE TITLE
Use type information from {templateType} and {varType}

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#72]

**Comment by lulco** [comment]
Why would we do that? They are not relevant and can cause wrong assumptions same as php doc var type

**Comment by MartinMystikJonas** [comment]
It can be used to cover some non standard situations. For templateType it would be great to compare it with provided templateType in render call and report mismatch

**Comment by MartinMystikJonas** [comment]
And for varType it coukd be useful when resolver collects union of assigned types but from context it is clear that given value cannot occur in template. For example there is assignes default that is always overriden before render call of given template.

**Comment by lulco** [comment]
Did you need it in your projects these days? I don't. I would close it, and try to write php code the way where no additional var types will be needed in latte

**Comment by MartinMystikJonas** [comment]
I have handful cases where varType would be useful. Mainly things tnat PHPStan cannot resolve correctly.

TemplateType would be usef to check against passed template type to spot mismatch errors.

Keep it open I will implement it later.

**Comment by lulco** [comment]
I'm definitely decided to not implement this. As @spaze proved in his app, it is not needed and can be successfully achieve level max with bleeding edge without varTypes / templateTypes in compiled files

**Comment by spaze** [comment]
Just for the record, I still use `{varType}` / `{templateType}` but just to tell my IDE where it should jump when I click on the variable.

**Comment by lulco** [comment]
Yes, but it's just for IDE and developer. Extension don’t need it.
