### ISSUE TITLE
Report unchecked latte files (optionally) 

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#73]
Find all latte files in analysedPaths. When file is analysed remove it from list. Then report all files left on list because they were unchecked. Make it optional but it would be very useful to find blind spots of analysis caused by some non standard render calls (for example with dynamically generated template path) .

**Comment by MartinMystikJonas** [comment]
Solved by #87

**Comment by lulco** [comment]
Close issue after merge - it is done automatically if you add comment “Resolves #xxx” to PR description
