### ISSUE TITLE
Presenters: Different template and render method when action uses setView

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#91]
Presenter action can call setView to use different render method and template than defaukt derived from action name.

Probably add ViewChangeCollector and evaluate it in presenter resolver.

**Comment by lulco** [comment]
You can also call ->setFile in action / render

**Comment by MartinMystikJonas** [comment]
I think it is already covered

**Comment by lulco** [comment]
OK then there is some problem in my apps :)

**Comment by MartinMystikJonas** [comment]
Checked the code. It looks only for explicit renders and always check both explicit render and default template.

**Comment by MartinMystikJonas** [comment]
Can you prepare test case? I will look at it.

**Comment by MartinMystikJonas** [comment]
Check #149 Add more test cases if you can think about any
