### ISSUE TITLE
Custom filter registration

### ISSUE THREAD

**Issue by jakubvojacek** [efabrica-team/phpstan-latte#97]
Hello

do we have to manually register filters or is it enough to provide the engine bootstrap file? 

```
...
engineBootstrap: phpstan.latte.engine.php
...
```

```php
<?php

$container = require_once "app/bootstrap.php";


return $container->getService('latte.templateFactory')->createTemplate()->getLatte();
```

But phpstan still complaints about all my custom filters. I checked `->getFilters()` on the `getLatte()` and the filters were returned therefore I believe phpstan should be aware of them. But apparently not

Since this extension is still in very active development, is it too early to report this? Should I wait some more weeks?

Thanks

**Comment by MartinMystikJonas** [comment]
Thanks for report.  What version of Latte do you use? For latte 3 it should work for filters added by extensions. For latte 2 there is problem that we cannot get filter signatures we need just filter names. I have some idea how to get to this info using reflection but it is not yet implemented.

**Comment by jakubvojacek** [comment]
3.0.4, the very latest. The filters are added in config.neon

```
services: 
	installLatteFilters: Motv\FrontModule\Lib\InstallLatteFilterMacros
	latte.latteFactory:
		setup:
			- @installLatteFilters::install(@self)
```

and 

```php
...
public function install(Latte\Engine $template): void
	{
		$template->addFilter('markdown', static function (string $text): string {
			$parser = new \Parsedown();

			return $parser->parse($text);
		});
....
```

**Comment by MartinMystikJonas** [comment]
Ok this is not supported yet in Latte3. Only filters added by extensions.

**Comment by MartinMystikJonas** [comment]
For now you can either add filters in config or rewrite you code to use Latte 3 extension for filter registration. I will try to solve it for directly added filters in the future.

**Comment by jakubvojacek** [comment]
> For now you can either add filters in config or rewrite you code to use Latte 3 extension for filter registration

not sure which part of the docs describes this, is there some github sample in some project or nette docs? I thought I was doing it correctly - its how I found it described by dg in some thread on nette forums

Thanks

**Comment by MartinMystikJonas** [comment]
Documentation: https://latte.nette.org/cs/creating-extension
Tutorial by @dg: https://forum.nette.org/cs/35241-latte-3-a-extension-pro-kazdy-webovy-projekt

**Comment by jakubvojacek** [comment]
Thanks, the forum post seems like a spot-on. I will rewrite my code according to that.

I was searching for the docs in english (as I am used to searching for everything) and forgot that its purely czech fw :)

Should I close this issue?

Thanks

**Comment by dg** [comment]
Purely czech??

https://latte.nette.org/en/creating-extension
https://latte.nette.org/en/cookbook/migration-from-latte2

**Comment by jakubvojacek** [comment]
> Purely czech??

I read both of these but neither mentions how to register it in neon. By reading the czech forum post I knew in about 5 seconds exactly how to create and register the extension.

**Comment by dg** [comment]
https://doc.nette.org/en/configuring
